### ISSUE TITLE
Feature #3:  Windows auto resize

### ISSUE THREAD

**Issue by larocquemb** [dlarocque/AlgorithmVisualizer#15] opened 2020-08-14 11:38 UTC
Would be nice if application would detect screen resolution and resize accordingly.

**Comment by dlarocque** [comment] 2020-08-16 22:17
Duplicate of #5

**Comment by dlarocque** [comment] 2020-08-18 20:22
The options for the size of the array are based on the width and height of the content pane because certain sizes will not let the array be painted correctly.
Would need to take off the array size options and instead adjust the size of the array based on the size of the window.

**Closed** 2020-08-25 02:12 UTC
Labels: wontfix
